name: Build & Test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Sets up JDK 1.8 as using standard setup
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    # Run against supported Minecraft versions
    - name: Build and test (Minecraft version = latest release, variant = vanilla)
      run: bin/ci.sh --clean
    - name: Build and test (Minecraft version = latest release, variant = paper)
      run: bin/ci.sh --clean --variant paper
    - name: Build and test (Minecraft version = 1.15.2, variant = vanilla)
      run: bin/ci.sh --clean --version 1.15.2
    - name: Build and test (Minecraft version = 1.15.2, variant = paper)
      run: bin/ci.sh --clean --version 1.15.2 --variant paper
